[package]
name = "wayland"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
nix = { workspace = true }
rustix = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
